version: '3.8'

services:
 postgres:
    restart: always
    container_name: py_prac_7_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ch_postgres_db
    ports:
      - '6543:5432'
    volumes:
      - ./postgres/container_data:/var/lib/postgresql/data
    build: 
      dockerfile: postgres/Dockerfile


 liquibase:
    container_name: py_prac_7_liquibase
    restart: on-failure
    depends_on:
      - postgres
    environment:
      LIQUIBASE_SEARCH_PATH: ./changelog
    build:
      dockerfile: liquibase/Dockerfile
    command: liquibase --url="jdbc:postgresql://postgres:5432/ch_postgres_db" --changeLogFile=liquibase-changelog.xml --username=postgres --password=postgres update


networks:
  my_network:
    driver: bridge